# version: '3.8'

services:
  auth_migrations:
    container_name: auth_migrations
    build:
      context: ..
      dockerfile: migration/Dockerfile.migrations
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTIONSTRING}
    restart: "no"
    env_file:
      - .env
    networks:
      - postgree_app-network

networks:
  postgree_app-network:
    external: true