services:

  tf-auth:
    container_name: tf-auth

    build:
      context: ../AuthService
      dockerfile: Dockerfile

    networks:
      - think-fast-net
      - postgree_app-network

    volumes:
      - tf-auth-keys:/keys

    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS:-8080}
      Jwt__PrivateKeyPath: ${Jwt__PrivateKeyPath}
      Jwt__Issuer: ${Jwt__Issuer:-auth-service}
      Jwt__Audience: ${Jwt__Audience:-api}
      ConnectionStrings__DefaultConnection: "Host=${POSTGRES_HOST:-tf-postgres};Port=${POSTGRES_PORT:-5432};Database=${POSTGRES_DB:-tf};Username=${POSTGRES_USER:-tf};Password=${POSTGRES_PASSWORD}"
      Redis__ConnectionString: ${Redis__ConnectionString:-tf-redis:6379}
      
    healthcheck:
      test:
        [
           "CMD",
           "curl",
           "-f",
           "http://tf-auth:8081/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

    restart: unless-stopped

networks:
  think-fast-net:
    external: true
  postgree_app-network:
    external: true

volumes:
  tf-auth-keys: