services:

  tf-auth:
    container_name: tf-auth

    build:
      context: ../AuthService
      dockerfile: Dockerfile

    networks:
      - think-fast-net

    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS:-8080}
      Jwt__PrivateKeyPath: ${Jwt__PrivateKeyPath}

    healthcheck:
      test:
        [
           "CMD",
           "curl",
           "-f",
           "http://localhost:8081/health"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

    restart: unless-stopped

networks:
  think-fast-net:
    external: true